archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-elasticstack
    dir: provider
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ignore: []
    ldflags:
      - -X github.com/zlepper/pulumi-elasticstack/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-elasticstack/
release:
  disable: false
  github:
    owner: zlepper
    name: "pulumi-elastickstack"
  skip_upload: true
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
