// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Outputs
{

    [OutputType]
    public sealed class IndexTemplateDataStream
    {
        /// <summary>
        /// If `true`, the data stream supports custom routing. Defaults to `false`. Available only in **8.x**
        /// </summary>
        public readonly bool? AllowCustomRouting;
        /// <summary>
        /// If true, the data stream is hidden.
        /// </summary>
        public readonly bool? Hidden;

        [OutputConstructor]
        private IndexTemplateDataStream(
            bool? allowCustomRouting,

            bool? hidden)
        {
            AllowCustomRouting = allowCustomRouting;
            Hidden = hidden;
        }
    }
}
