// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Outputs
{

    [OutputType]
    public sealed class SnapshotRepositoryS3
    {
        /// <summary>
        /// Specifies the path to the repository data within its bucket.
        /// </summary>
        public readonly string? BasePath;
        /// <summary>
        /// Name of the S3 bucket to use for snapshots.
        /// </summary>
        public readonly string Bucket;
        /// <summary>
        /// Minimum threshold below which the chunk is uploaded using a single request.
        /// </summary>
        public readonly string? BufferSize;
        /// <summary>
        /// The S3 repository supports all S3 canned ACLs.
        /// </summary>
        public readonly string? CannedAcl;
        /// <summary>
        /// Maximum size of files in snapshots.
        /// </summary>
        public readonly string? ChunkSize;
        /// <summary>
        /// The name of the S3 client to use to connect to S3.
        /// </summary>
        public readonly string? Client;
        /// <summary>
        /// If true, metadata files, such as index mappings and settings, are compressed in snapshots.
        /// </summary>
        public readonly bool? Compress;
        /// <summary>
        /// Maximum snapshot restore rate per node.
        /// </summary>
        public readonly string? MaxRestoreBytesPerSec;
        /// <summary>
        /// Maximum snapshot creation rate per node.
        /// </summary>
        public readonly string? MaxSnapshotBytesPerSec;
        /// <summary>
        /// If true, the repository is read-only.
        /// </summary>
        public readonly bool? Readonly;
        /// <summary>
        /// When true, files are encrypted server-side using AES-256 algorithm.
        /// </summary>
        public readonly bool? ServerSideEncryption;
        /// <summary>
        /// Sets the S3 storage class for objects stored in the snapshot repository.
        /// </summary>
        public readonly string? StorageClass;

        [OutputConstructor]
        private SnapshotRepositoryS3(
            string? basePath,

            string bucket,

            string? bufferSize,

            string? cannedAcl,

            string? chunkSize,

            string? client,

            bool? compress,

            string? maxRestoreBytesPerSec,

            string? maxSnapshotBytesPerSec,

            bool? @readonly,

            bool? serverSideEncryption,

            string? storageClass)
        {
            BasePath = basePath;
            Bucket = bucket;
            BufferSize = bufferSize;
            CannedAcl = cannedAcl;
            ChunkSize = chunkSize;
            Client = client;
            Compress = compress;
            MaxRestoreBytesPerSec = maxRestoreBytesPerSec;
            MaxSnapshotBytesPerSec = maxSnapshotBytesPerSec;
            Readonly = @readonly;
            ServerSideEncryption = serverSideEncryption;
            StorageClass = storageClass;
        }
    }
}
