// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Inputs
{

    public sealed class IndexLifecycleDeleteGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Permanently removes the index.
        /// </summary>
        [Input("delete")]
        public Input<Inputs.IndexLifecycleDeleteDeleteGetArgs>? Delete { get; set; }

        /// <summary>
        /// ILM moves indices through the lifecycle according to their age. To control the timing of these transitions, you set a minimum age for each phase.
        /// </summary>
        [Input("minAge")]
        public Input<string>? MinAge { get; set; }

        /// <summary>
        /// Waits for the specified SLM policy to be executed before removing the index. This ensures that a snapshot of the deleted index is available.
        /// </summary>
        [Input("waitForSnapshot")]
        public Input<Inputs.IndexLifecycleDeleteWaitForSnapshotGetArgs>? WaitForSnapshot { get; set; }

        public IndexLifecycleDeleteGetArgs()
        {
        }
        public static new IndexLifecycleDeleteGetArgs Empty => new IndexLifecycleDeleteGetArgs();
    }
}
