// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Inputs
{

    public sealed class IndexTemplateDataStreamGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If `true`, the data stream supports custom routing. Defaults to `false`. Available only in **8.x**
        /// </summary>
        [Input("allowCustomRouting")]
        public Input<bool>? AllowCustomRouting { get; set; }

        /// <summary>
        /// If true, the data stream is hidden.
        /// </summary>
        [Input("hidden")]
        public Input<bool>? Hidden { get; set; }

        public IndexTemplateDataStreamGetArgs()
        {
        }
        public static new IndexTemplateDataStreamGetArgs Empty => new IndexTemplateDataStreamGetArgs();
    }
}
