// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Inputs
{

    public sealed class SecurityRoleIndexFieldSecurityArgs : global::Pulumi.ResourceArgs
    {
        [Input("excepts")]
        private InputList<string>? _excepts;
        public InputList<string> Excepts
        {
            get => _excepts ?? (_excepts = new InputList<string>());
            set => _excepts = value;
        }

        [Input("grants")]
        private InputList<string>? _grants;
        public InputList<string> Grants
        {
            get => _grants ?? (_grants = new InputList<string>());
            set => _grants = value;
        }

        public SecurityRoleIndexFieldSecurityArgs()
        {
        }
        public static new SecurityRoleIndexFieldSecurityArgs Empty => new SecurityRoleIndexFieldSecurityArgs();
    }
}
