// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get information about existing Elasticsearch user. See, https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-user.html".
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"github.com/zlepper/pulumi-elasticstack/sdk/go/elasticstack"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		userSecurityUser, err := elasticstack.LookupSecurityUser(ctx, &elasticstack.LookupSecurityUserArgs{
// 			Username: "elastic",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("user", userSecurityUser)
// 		return nil
// 	})
// }
// ```
func LookupSecurityUser(ctx *pulumi.Context, args *LookupSecurityUserArgs, opts ...pulumi.InvokeOption) (*LookupSecurityUserResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupSecurityUserResult
	err := ctx.Invoke("elasticstack:index/getSecurityUser:getSecurityUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSecurityUser.
type LookupSecurityUserArgs struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection *GetSecurityUserElasticsearchConnection `pulumi:"elasticsearchConnection"`
	// An identifier for the user
	Username string `pulumi:"username"`
}

// A collection of values returned by getSecurityUser.
type LookupSecurityUserResult struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection *GetSecurityUserElasticsearchConnection `pulumi:"elasticsearchConnection"`
	// The email of the user.
	Email string `pulumi:"email"`
	// Specifies whether the user is enabled. The default value is true.
	Enabled bool `pulumi:"enabled"`
	// The full name of the user.
	FullName string `pulumi:"fullName"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Arbitrary metadata that you want to associate with the user.
	Metadata string `pulumi:"metadata"`
	// A set of roles the user has. The roles determine the user’s access permissions. Default is [].
	Roles []string `pulumi:"roles"`
	// An identifier for the user
	Username string `pulumi:"username"`
}

func LookupSecurityUserOutput(ctx *pulumi.Context, args LookupSecurityUserOutputArgs, opts ...pulumi.InvokeOption) LookupSecurityUserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSecurityUserResult, error) {
			args := v.(LookupSecurityUserArgs)
			r, err := LookupSecurityUser(ctx, &args, opts...)
			var s LookupSecurityUserResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSecurityUserResultOutput)
}

// A collection of arguments for invoking getSecurityUser.
type LookupSecurityUserOutputArgs struct {
	// Elasticsearch connection configuration block.
	ElasticsearchConnection GetSecurityUserElasticsearchConnectionPtrInput `pulumi:"elasticsearchConnection"`
	// An identifier for the user
	Username pulumi.StringInput `pulumi:"username"`
}

func (LookupSecurityUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecurityUserArgs)(nil)).Elem()
}

// A collection of values returned by getSecurityUser.
type LookupSecurityUserResultOutput struct{ *pulumi.OutputState }

func (LookupSecurityUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecurityUserResult)(nil)).Elem()
}

func (o LookupSecurityUserResultOutput) ToLookupSecurityUserResultOutput() LookupSecurityUserResultOutput {
	return o
}

func (o LookupSecurityUserResultOutput) ToLookupSecurityUserResultOutputWithContext(ctx context.Context) LookupSecurityUserResultOutput {
	return o
}

// Elasticsearch connection configuration block.
func (o LookupSecurityUserResultOutput) ElasticsearchConnection() GetSecurityUserElasticsearchConnectionPtrOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) *GetSecurityUserElasticsearchConnection {
		return v.ElasticsearchConnection
	}).(GetSecurityUserElasticsearchConnectionPtrOutput)
}

// The email of the user.
func (o LookupSecurityUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) string { return v.Email }).(pulumi.StringOutput)
}

// Specifies whether the user is enabled. The default value is true.
func (o LookupSecurityUserResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// The full name of the user.
func (o LookupSecurityUserResultOutput) FullName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) string { return v.FullName }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o LookupSecurityUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) string { return v.Id }).(pulumi.StringOutput)
}

// Arbitrary metadata that you want to associate with the user.
func (o LookupSecurityUserResultOutput) Metadata() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) string { return v.Metadata }).(pulumi.StringOutput)
}

// A set of roles the user has. The roles determine the user’s access permissions. Default is [].
func (o LookupSecurityUserResultOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) []string { return v.Roles }).(pulumi.StringArrayOutput)
}

// An identifier for the user
func (o LookupSecurityUserResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityUserResult) string { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSecurityUserResultOutput{})
}
