// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Updates cluster-wide settings. If the Elasticsearch security features are enabled, you must have the manage cluster privilege to use this API. See, https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html
 */
export class ClusterSettings extends pulumi.CustomResource {
    /**
     * Get an existing ClusterSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterSettingsState, opts?: pulumi.CustomResourceOptions): ClusterSettings {
        return new ClusterSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'elasticstack:index/clusterSettings:ClusterSettings';

    /**
     * Returns true if the given object is an instance of ClusterSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterSettings.__pulumiType;
    }

    /**
     * Elasticsearch connection configuration block.
     */
    public readonly elasticsearchConnection!: pulumi.Output<outputs.ClusterSettingsElasticsearchConnection | undefined>;
    /**
     * Settings will apply across restarts.
     */
    public readonly persistent!: pulumi.Output<outputs.ClusterSettingsPersistent | undefined>;
    /**
     * Settings do not survive a full cluster restart.
     */
    public readonly transient!: pulumi.Output<outputs.ClusterSettingsTransient | undefined>;

    /**
     * Create a ClusterSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClusterSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterSettingsArgs | ClusterSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClusterSettingsState | undefined;
            resourceInputs["elasticsearchConnection"] = state ? state.elasticsearchConnection : undefined;
            resourceInputs["persistent"] = state ? state.persistent : undefined;
            resourceInputs["transient"] = state ? state.transient : undefined;
        } else {
            const args = argsOrState as ClusterSettingsArgs | undefined;
            resourceInputs["elasticsearchConnection"] = args ? args.elasticsearchConnection : undefined;
            resourceInputs["persistent"] = args ? args.persistent : undefined;
            resourceInputs["transient"] = args ? args.transient : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterSettings.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ClusterSettings resources.
 */
export interface ClusterSettingsState {
    /**
     * Elasticsearch connection configuration block.
     */
    elasticsearchConnection?: pulumi.Input<inputs.ClusterSettingsElasticsearchConnection>;
    /**
     * Settings will apply across restarts.
     */
    persistent?: pulumi.Input<inputs.ClusterSettingsPersistent>;
    /**
     * Settings do not survive a full cluster restart.
     */
    transient?: pulumi.Input<inputs.ClusterSettingsTransient>;
}

/**
 * The set of arguments for constructing a ClusterSettings resource.
 */
export interface ClusterSettingsArgs {
    /**
     * Elasticsearch connection configuration block.
     */
    elasticsearchConnection?: pulumi.Input<inputs.ClusterSettingsElasticsearchConnection>;
    /**
     * Settings will apply across restarts.
     */
    persistent?: pulumi.Input<inputs.ClusterSettingsPersistent>;
    /**
     * Settings do not survive a full cluster restart.
     */
    transient?: pulumi.Input<inputs.ClusterSettingsTransient>;
}
