// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Splits a field into an array using a separator character. Only works on string fields.
 *
 * See: https://www.elastic.co/guide/en/elasticsearch/reference/current/split-processor.html
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as elasticstack from "@pulumi/elasticstack";
 *
 * const split = elasticstack.getIngestProcessorSplit({
 *     field: "my_field",
 *     separator: "\\s+",
 * });
 * const myIngestPipeline = new elasticstack.IngestPipeline("myIngestPipeline", {processors: [split.then(split => split.json)]});
 * ```
 */
export function getIngestProcessorSplit(args: GetIngestProcessorSplitArgs, opts?: pulumi.InvokeOptions): Promise<GetIngestProcessorSplitResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("elasticstack:index/getIngestProcessorSplit:getIngestProcessorSplit", {
        "description": args.description,
        "field": args.field,
        "if": args.if,
        "ignoreFailure": args.ignoreFailure,
        "ignoreMissing": args.ignoreMissing,
        "onFailures": args.onFailures,
        "preserveTrailing": args.preserveTrailing,
        "separator": args.separator,
        "tag": args.tag,
        "targetField": args.targetField,
    }, opts);
}

/**
 * A collection of arguments for invoking getIngestProcessorSplit.
 */
export interface GetIngestProcessorSplitArgs {
    /**
     * Description of the processor.
     */
    description?: string;
    /**
     * The field to split
     */
    field: string;
    /**
     * Conditionally execute the processor
     */
    if?: string;
    /**
     * Ignore failures for the processor.
     */
    ignoreFailure?: boolean;
    /**
     * If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
     */
    ignoreMissing?: boolean;
    /**
     * Handle failures for the processor.
     */
    onFailures?: string[];
    /**
     * Preserves empty trailing fields, if any.
     */
    preserveTrailing?: boolean;
    /**
     * A regex which matches the separator, eg `,` or `\s+`
     */
    separator: string;
    /**
     * Identifier for the processor.
     */
    tag?: string;
    /**
     * The field to assign the converted value to, by default `field` is updated in-place.
     */
    targetField?: string;
}

/**
 * A collection of values returned by getIngestProcessorSplit.
 */
export interface GetIngestProcessorSplitResult {
    /**
     * Description of the processor.
     */
    readonly description?: string;
    /**
     * The field to split
     */
    readonly field: string;
    /**
     * Internal identifier of the resource.
     */
    readonly id: string;
    /**
     * Conditionally execute the processor
     */
    readonly if?: string;
    /**
     * Ignore failures for the processor.
     */
    readonly ignoreFailure?: boolean;
    /**
     * If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
     */
    readonly ignoreMissing?: boolean;
    /**
     * JSON representation of this data source.
     */
    readonly json: string;
    /**
     * Handle failures for the processor.
     */
    readonly onFailures?: string[];
    /**
     * Preserves empty trailing fields, if any.
     */
    readonly preserveTrailing?: boolean;
    /**
     * A regex which matches the separator, eg `,` or `\s+`
     */
    readonly separator: string;
    /**
     * Identifier for the processor.
     */
    readonly tag?: string;
    /**
     * The field to assign the converted value to, by default `field` is updated in-place.
     */
    readonly targetField?: string;
}
/**
 * Splits a field into an array using a separator character. Only works on string fields.
 *
 * See: https://www.elastic.co/guide/en/elasticsearch/reference/current/split-processor.html
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as elasticstack from "@pulumi/elasticstack";
 *
 * const split = elasticstack.getIngestProcessorSplit({
 *     field: "my_field",
 *     separator: "\\s+",
 * });
 * const myIngestPipeline = new elasticstack.IngestPipeline("myIngestPipeline", {processors: [split.then(split => split.json)]});
 * ```
 */
export function getIngestProcessorSplitOutput(args: GetIngestProcessorSplitOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIngestProcessorSplitResult> {
    return pulumi.output(args).apply((a: any) => getIngestProcessorSplit(a, opts))
}

/**
 * A collection of arguments for invoking getIngestProcessorSplit.
 */
export interface GetIngestProcessorSplitOutputArgs {
    /**
     * Description of the processor.
     */
    description?: pulumi.Input<string>;
    /**
     * The field to split
     */
    field: pulumi.Input<string>;
    /**
     * Conditionally execute the processor
     */
    if?: pulumi.Input<string>;
    /**
     * Ignore failures for the processor.
     */
    ignoreFailure?: pulumi.Input<boolean>;
    /**
     * If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
     */
    ignoreMissing?: pulumi.Input<boolean>;
    /**
     * Handle failures for the processor.
     */
    onFailures?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Preserves empty trailing fields, if any.
     */
    preserveTrailing?: pulumi.Input<boolean>;
    /**
     * A regex which matches the separator, eg `,` or `\s+`
     */
    separator: pulumi.Input<string>;
    /**
     * Identifier for the processor.
     */
    tag?: pulumi.Input<string>;
    /**
     * The field to assign the converted value to, by default `field` is updated in-place.
     */
    targetField?: pulumi.Input<string>;
}
